# Copyright 2018/4 tteat
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# service 1
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: service1
spec:
  ports:
  - port: 9088
    name: http
  selector:
    app: service1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
        version: v1
    spec:
      containers:
      - name: service1
        image: tteatt/service1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9088
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 600Mi
---
##################################################################################################
# service 2
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: service2
spec:
  ports:
  - port: 9088
    name: http
  selector:
    app: service2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
        version: v1
    spec:
      containers:
      - name: service2
        image: tteatt/service2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9088
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
---
##################################################################################################
# service 3
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app: service3
spec:
  ports:
  - port: 9088
    name: http
  selector:
    app: service3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service3
        version: v1
    spec:
      containers:
      - name: service3
        image: tteatt/service3:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9088
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
---
###########################################################################
# Ingress resource 
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demogateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /chaining
        backend:
          serviceName: service1
          servicePort: 9088
---
